namespace TbotUltra.Core.Configuration;

public static class BotOptionsPayloadApplier
{
    public static BotOptions Apply(BotOptions source, IReadOnlyDictionary<string, string>? payload)
    {
        var construction = ConstructionPayloadApplier.Apply(source, payload);
        var targetVillageName = construction.TargetVillageName;
        var targetVillageUrl = construction.TargetVillageUrl;
        var resourceUpgradeSlotId = construction.ResourceUpgradeSlotId;
        var resourceUpgradeTargetLevel = construction.ResourceUpgradeTargetLevel;
        var resourceUpgradeMaxAttempts = construction.ResourceUpgradeMaxAttempts;
        var resourceBuildStrategy = construction.ResourceBuildStrategy;
        var smithyUpgradeTargets = construction.SmithyUpgradeTargets;
        var buildingUpgradeSlotId = construction.BuildingUpgradeSlotId;
        var buildingUpgradeTargetLevel = construction.BuildingUpgradeTargetLevel;
        var buildingUpgradeMaxAttempts = construction.BuildingUpgradeMaxAttempts;
        var buildingConstructSlotId = construction.BuildingConstructSlotId;
        var buildingConstructGid = construction.BuildingConstructGid;
        var buildingConstructName = construction.BuildingConstructName;
        var constructFasterEnabled = construction.ConstructFasterEnabled;
        var constructFasterMinBuildTimeEnabled = construction.ConstructFasterMinBuildTimeEnabled;
        var constructFasterMinBuildMinutes = construction.ConstructFasterMinBuildMinutes;
        var constructFasterRandomEnabled = construction.ConstructFasterRandomEnabled;
        var constructFasterRandomChancePercent = construction.ConstructFasterRandomChancePercent;
        var targetBuildingSlotOrName = construction.TargetBuildingSlotOrName;
        var targetLevel = construction.TargetLevel;
        var hero = HeroPayloadApplier.Apply(source, payload);
        var heroMinHpForAdventure = hero.MinHpForAdventure;
        var heroAutoRevive = hero.AutoRevive;
        var heroAutoAssignPoints = hero.AutoAssignPoints;
        var heroAutoUseOintments = hero.AutoUseOintments;
        var heroStatPriority = hero.StatPriority;
        var heroAdventurePickOrder = hero.AdventurePickOrder;
        var heroContinuousAdventures = hero.ContinuousAdventures;
        var increaseAdventuresToHard = hero.IncreaseAdventuresToHard;
        var reduceAdventureTime = hero.ReduceAdventureTime;
        var heroAdventureVideoChancePercent = hero.AdventureVideoChancePercent;
        var autoCollectTasksEnabled = hero.AutoCollectTasksEnabled;
        var autoCollectDailyQuestsEnabled = hero.AutoCollectDailyQuestsEnabled;
        var productionBonusVideoEnabled = hero.ProductionBonusVideoEnabled;
        var collectStepDelayMinSeconds = hero.CollectStepDelayMinSeconds;
        var collectStepDelayMaxSeconds = hero.CollectStepDelayMaxSeconds;
        var heroResourceTransferEnabled = hero.ResourceTransferEnabled;
        var heroResourceMaxUseEnabled = hero.ResourceMaxUseEnabled;
        var heroResourceMaxUsePerResource = hero.ResourceMaxUsePerResource;
        var heroResourceUseConstruction = hero.ResourceUseConstruction;
        var heroResourceUseSmithy = hero.ResourceUseSmithy;
        var heroResourceUseBrewery = hero.ResourceUseBrewery;
        var heroResourceUseTownHall = hero.ResourceUseTownHall;
        var upgradeSelectorProfile = construction.UpgradeSelectorProfile;
        var farming = FarmingPayloadApplier.Apply(source, payload);
        var continuousFarmListNames = farming.ListNames;
        var continuousFarmListIds = farming.ListIds;
        var continuousFarmDispatchDelayMinutes = farming.DispatchDelayMinMinutes;
        var continuousFarmDispatchDelayVariationPercent = farming.DispatchDelayMaxMinutes;
        var continuousFarmSendMode = farming.SendMode;
        var townHallCelebrationMode = farming.TownHallCelebrationMode;
        var townHallCelebrationCount = source.TownHallCelebrationCount;
        var townHallCelebrationRestartDelayMinMinutes = source.TownHallCelebrationRestartDelayMinMinutes;
        var townHallCelebrationRestartDelayMaxMinutes = source.TownHallCelebrationRestartDelayMaxMinutes;
        var continuousFarmDeactivateLosses = farming.DeactivateLosses;
        var continuousFarmDeactivateOasisLosses = farming.DeactivateOasisLosses;
        var continuousFarmNextListIndex = farming.NextListIndex;
        var postLogin = PostLoginPayloadApplier.Apply(source, payload);
        var postLoginAnalyzeFarmlists = postLogin.AnalyzeFarmlists;
        var postLoginAnalyzeHero = postLogin.AnalyzeHero;
        var postLoginAnalyzeHeroInventory = postLogin.AnalyzeHeroInventory;
        var postLoginReadTroopTrainingQueue = postLogin.ReadTroopTrainingQueue;
        var postLoginAnalyzeBrewery = postLogin.AnalyzeBrewery;
        var postLoginAnalyzeNewVillages = postLogin.AnalyzeNewVillages;
        var automaticallyCheckLanguage = postLogin.AutomaticallyCheckLanguage;
        var troopTraining = TroopTrainingPayloadApplier.Apply(source, payload);
        var troopTrainingBarracksEnabled = troopTraining.Barracks.Enabled;
        var troopTrainingBarracksTroopType = troopTraining.Barracks.TroopType;
        var troopTrainingBarracksMaxQueueHours = troopTraining.Barracks.MaxQueueHours;
        var troopTrainingBarracksAmountMode = troopTraining.Barracks.AmountMode;
        var troopTrainingBarracksKeepResourcesPercent = troopTraining.Barracks.KeepResourcesPercent;
        var troopTrainingBarracksRunMode = troopTraining.Barracks.RunMode;
        var troopTrainingBarracksMinimumTroops = troopTraining.Barracks.MinimumTroops;
        var troopTrainingBarracksMinimumResourcesPercent = troopTraining.Barracks.MinimumResourcesPercent;
        var troopTrainingBarracksTimedMinMinutes = troopTraining.Barracks.TimedMinMinutes;
        var troopTrainingBarracksTimedMaxMinutes = troopTraining.Barracks.TimedMaxMinutes;
        var troopTrainingBarracksCheckWood = troopTraining.Barracks.CheckWood;
        var troopTrainingBarracksCheckClay = troopTraining.Barracks.CheckClay;
        var troopTrainingBarracksCheckIron = troopTraining.Barracks.CheckIron;
        var troopTrainingBarracksCheckCrop = troopTraining.Barracks.CheckCrop;
        var troopTrainingStableEnabled = troopTraining.Stable.Enabled;
        var troopTrainingStableTroopType = troopTraining.Stable.TroopType;
        var troopTrainingStableMaxQueueHours = troopTraining.Stable.MaxQueueHours;
        var troopTrainingStableAmountMode = troopTraining.Stable.AmountMode;
        var troopTrainingStableKeepResourcesPercent = troopTraining.Stable.KeepResourcesPercent;
        var troopTrainingStableRunMode = troopTraining.Stable.RunMode;
        var troopTrainingStableMinimumTroops = troopTraining.Stable.MinimumTroops;
        var troopTrainingStableMinimumResourcesPercent = troopTraining.Stable.MinimumResourcesPercent;
        var troopTrainingStableTimedMinMinutes = troopTraining.Stable.TimedMinMinutes;
        var troopTrainingStableTimedMaxMinutes = troopTraining.Stable.TimedMaxMinutes;
        var troopTrainingStableCheckWood = troopTraining.Stable.CheckWood;
        var troopTrainingStableCheckClay = troopTraining.Stable.CheckClay;
        var troopTrainingStableCheckIron = troopTraining.Stable.CheckIron;
        var troopTrainingStableCheckCrop = troopTraining.Stable.CheckCrop;
        var troopTrainingWorkshopEnabled = troopTraining.Workshop.Enabled;
        var troopTrainingWorkshopTroopType = troopTraining.Workshop.TroopType;
        var troopTrainingWorkshopMaxQueueHours = troopTraining.Workshop.MaxQueueHours;
        var troopTrainingWorkshopAmountMode = troopTraining.Workshop.AmountMode;
        var troopTrainingWorkshopKeepResourcesPercent = troopTraining.Workshop.KeepResourcesPercent;
        var troopTrainingWorkshopRunMode = troopTraining.Workshop.RunMode;
        var troopTrainingWorkshopMinimumTroops = troopTraining.Workshop.MinimumTroops;
        var troopTrainingWorkshopMinimumResourcesPercent = troopTraining.Workshop.MinimumResourcesPercent;
        var troopTrainingWorkshopTimedMinMinutes = troopTraining.Workshop.TimedMinMinutes;
        var troopTrainingWorkshopTimedMaxMinutes = troopTraining.Workshop.TimedMaxMinutes;
        var troopTrainingWorkshopCheckWood = troopTraining.Workshop.CheckWood;
        var troopTrainingWorkshopCheckClay = troopTraining.Workshop.CheckClay;
        var troopTrainingWorkshopCheckIron = troopTraining.Workshop.CheckIron;
        var troopTrainingWorkshopCheckCrop = troopTraining.Workshop.CheckCrop;
        var troopTrainingFallbackCooldownSeconds = troopTraining.FallbackCooldownSeconds;
        var breweryAutoCelebrationEnabled = troopTraining.BreweryAutoCelebrationEnabled;
        var npcTrade = NpcTradePayloadApplier.Apply(source, payload);
        var npcTradeEnabled = npcTrade.Enabled;
        var npcTradeConstructionEnabled = npcTrade.ConstructionEnabled;
        var npcTradeThresholdPercent = npcTrade.ThresholdPercent;
        var npcTradeAnalyzeWood = npcTrade.AnalyzeWood;
        var npcTradeAnalyzeClay = npcTrade.AnalyzeClay;
        var npcTradeAnalyzeIron = npcTrade.AnalyzeIron;
        var npcTradeAnalyzeCrop = npcTrade.AnalyzeCrop;
        var npcTradeBuildTimeLimitEnabled = npcTrade.BuildTimeLimitEnabled;
        var npcTradeBuildTimeLimitSeconds = npcTrade.BuildTimeLimitSeconds;
        var resourceTransfer = ResourceTransferPayloadApplier.Apply(source, payload);
        var resourceTransferEnabled = resourceTransfer.Enabled;
        var resourceTransferTargetVillageName = resourceTransfer.TargetVillageName;
        var resourceTransferSourceVillageNames = resourceTransfer.SourceVillageNames;
        var resourceTransferSourceThresholdPercent = resourceTransfer.SourceThresholdPercent;
        var resourceTransferSourceKeepPercent = resourceTransfer.SourceKeepPercent;
        var resourceTransferTargetFillPercent = resourceTransfer.TargetFillPercent;
        var resourceTransferSendWood = resourceTransfer.SendWood;
        var resourceTransferSendClay = resourceTransfer.SendClay;
        var resourceTransferSendIron = resourceTransfer.SendIron;
        var resourceTransferSendCrop = resourceTransfer.SendCrop;
        var reinforcements = ReinforcementPayloadApplier.Apply(source, payload);
        var reinforcementsEnabled = reinforcements.Enabled;
        var reinforcementsTargetVillageName = reinforcements.TargetVillageName;
        var reinforcementsSourceVillageNames = reinforcements.SourceVillageNames;
        var reinforcementsTroopRules = reinforcements.TroopRules;
        var reinforcementsSendIntervalHours = reinforcements.SendMinMinutes;
        var reinforcementsSendVariationPercent = reinforcements.SendMaxMinutes;
        var actionPacing = ActionPacingPayloadApplier.Apply(source, payload);
        var actionPacingEnabled = actionPacing.Enabled;
        var actionPacingTaskMinSeconds = actionPacing.TaskMinSeconds;
        var actionPacingTaskMaxSeconds = actionPacing.TaskMaxSeconds;
        var actionPacingPageLoadMinSeconds = actionPacing.PageLoadMinSeconds;
        var actionPacingPageLoadMaxSeconds = actionPacing.PageLoadMaxSeconds;
        var actionPacingClickMinSeconds = actionPacing.ClickMinSeconds;
        var actionPacingClickMaxSeconds = actionPacing.ClickMaxSeconds;
        var actionPacingLoopMinSeconds = actionPacing.LoopMinSeconds;
        var actionPacingLoopMaxSeconds = actionPacing.LoopMaxSeconds;
        var farmListStepDelayMinSeconds = actionPacing.FarmListStepMinSeconds;
        var farmListStepDelayMaxSeconds = actionPacing.FarmListStepMaxSeconds;

        return new BotOptions
        {
            ServerName = source.ServerName,
            BaseUrl = source.BaseUrl,
            TimeoutMs = source.TimeoutMs,
            ManualLoginTimeoutSeconds = source.ManualLoginTimeoutSeconds,
            LoopIntervalSeconds = source.LoopIntervalSeconds,
            LoopTasks = source.LoopTasks,
            ContinuousLoopGroups = source.ContinuousLoopGroups,
            ContinuousFarmListNames = continuousFarmListNames,
            ContinuousFarmListIds = continuousFarmListIds,
            ContinuousFarmDispatchDelayMinMinutes = continuousFarmDispatchDelayMinutes,
            ContinuousFarmDispatchDelayMaxMinutes = continuousFarmDispatchDelayVariationPercent,
            ContinuousFarmSendMode = continuousFarmSendMode,
            TownHallCelebrationMode = townHallCelebrationMode,
            TownHallCelebrationCount = townHallCelebrationCount,
            TownHallCelebrationRestartDelayMinMinutes = townHallCelebrationRestartDelayMinMinutes,
            TownHallCelebrationRestartDelayMaxMinutes = townHallCelebrationRestartDelayMaxMinutes,
            ContinuousFarmDeactivateLosses = continuousFarmDeactivateLosses,
            ContinuousFarmDeactivateOasisLosses = continuousFarmDeactivateOasisLosses,
            ContinuousFarmNextListIndex = continuousFarmNextListIndex,
            PostLoginAnalyzeFarmlists = postLoginAnalyzeFarmlists,
            PostLoginAnalyzeHero = postLoginAnalyzeHero,
            PostLoginAnalyzeHeroInventory = postLoginAnalyzeHeroInventory,
            PostLoginReadTroopTrainingQueue = postLoginReadTroopTrainingQueue,
            PostLoginAnalyzeBrewery = postLoginAnalyzeBrewery,
            PostLoginAnalyzeNewVillages = postLoginAnalyzeNewVillages,
            AutomaticallyCheckLanguage = automaticallyCheckLanguage,
            DetailedBrowserLoggingEnabled = source.DetailedBrowserLoggingEnabled,
            TroopTrainingBarracksEnabled = troopTrainingBarracksEnabled,
            TroopTrainingBarracksTroopType = troopTrainingBarracksTroopType,
            TroopTrainingBarracksMaxQueueHours = troopTrainingBarracksMaxQueueHours,
            TroopTrainingBarracksAmountMode = troopTrainingBarracksAmountMode,
            TroopTrainingBarracksKeepResourcesPercent = troopTrainingBarracksKeepResourcesPercent,
            TroopTrainingBarracksRunMode = troopTrainingBarracksRunMode,
            TroopTrainingBarracksMinimumTroops = troopTrainingBarracksMinimumTroops,
            TroopTrainingBarracksMinimumResourcesPercent = troopTrainingBarracksMinimumResourcesPercent,
            TroopTrainingBarracksTimedMinMinutes = troopTrainingBarracksTimedMinMinutes,
            TroopTrainingBarracksTimedMaxMinutes = troopTrainingBarracksTimedMaxMinutes,
            TroopTrainingBarracksCheckWood = troopTrainingBarracksCheckWood,
            TroopTrainingBarracksCheckClay = troopTrainingBarracksCheckClay,
            TroopTrainingBarracksCheckIron = troopTrainingBarracksCheckIron,
            TroopTrainingBarracksCheckCrop = troopTrainingBarracksCheckCrop,
            TroopTrainingStableEnabled = troopTrainingStableEnabled,
            TroopTrainingStableTroopType = troopTrainingStableTroopType,
            TroopTrainingStableMaxQueueHours = troopTrainingStableMaxQueueHours,
            TroopTrainingStableAmountMode = troopTrainingStableAmountMode,
            TroopTrainingStableKeepResourcesPercent = troopTrainingStableKeepResourcesPercent,
            TroopTrainingStableRunMode = troopTrainingStableRunMode,
            TroopTrainingStableMinimumTroops = troopTrainingStableMinimumTroops,
            TroopTrainingStableMinimumResourcesPercent = troopTrainingStableMinimumResourcesPercent,
            TroopTrainingStableTimedMinMinutes = troopTrainingStableTimedMinMinutes,
            TroopTrainingStableTimedMaxMinutes = troopTrainingStableTimedMaxMinutes,
            TroopTrainingStableCheckWood = troopTrainingStableCheckWood,
            TroopTrainingStableCheckClay = troopTrainingStableCheckClay,
            TroopTrainingStableCheckIron = troopTrainingStableCheckIron,
            TroopTrainingStableCheckCrop = troopTrainingStableCheckCrop,
            TroopTrainingWorkshopEnabled = troopTrainingWorkshopEnabled,
            TroopTrainingWorkshopTroopType = troopTrainingWorkshopTroopType,
            TroopTrainingWorkshopMaxQueueHours = troopTrainingWorkshopMaxQueueHours,
            TroopTrainingWorkshopAmountMode = troopTrainingWorkshopAmountMode,
            TroopTrainingWorkshopKeepResourcesPercent = troopTrainingWorkshopKeepResourcesPercent,
            TroopTrainingWorkshopRunMode = troopTrainingWorkshopRunMode,
            TroopTrainingWorkshopMinimumTroops = troopTrainingWorkshopMinimumTroops,
            TroopTrainingWorkshopMinimumResourcesPercent = troopTrainingWorkshopMinimumResourcesPercent,
            TroopTrainingWorkshopTimedMinMinutes = troopTrainingWorkshopTimedMinMinutes,
            TroopTrainingWorkshopTimedMaxMinutes = troopTrainingWorkshopTimedMaxMinutes,
            TroopTrainingWorkshopCheckWood = troopTrainingWorkshopCheckWood,
            TroopTrainingWorkshopCheckClay = troopTrainingWorkshopCheckClay,
            TroopTrainingWorkshopCheckIron = troopTrainingWorkshopCheckIron,
            TroopTrainingWorkshopCheckCrop = troopTrainingWorkshopCheckCrop,
            TroopTrainingFallbackCooldownSeconds = troopTrainingFallbackCooldownSeconds,
            BreweryAutoCelebrationEnabled = breweryAutoCelebrationEnabled,
            NpcTradeEnabled = npcTradeEnabled,
            NpcTradeConstructionEnabled = npcTradeConstructionEnabled,
            NpcTradeThresholdPercent = npcTradeThresholdPercent,
            NpcTradeAnalyzeWood = npcTradeAnalyzeWood,
            NpcTradeAnalyzeClay = npcTradeAnalyzeClay,
            NpcTradeAnalyzeIron = npcTradeAnalyzeIron,
            NpcTradeAnalyzeCrop = npcTradeAnalyzeCrop,
            NpcTradeBuildTimeLimitEnabled = npcTradeBuildTimeLimitEnabled,
            NpcTradeBuildTimeLimitSeconds = npcTradeBuildTimeLimitSeconds,
            ResourceTransferEnabled = resourceTransferEnabled,
            ResourceTransferTargetVillageName = resourceTransferTargetVillageName,
            ResourceTransferSourceVillageNames = resourceTransferSourceVillageNames,
            ResourceTransferSourceThresholdPercent = resourceTransferSourceThresholdPercent,
            ResourceTransferSourceKeepPercent = resourceTransferSourceKeepPercent,
            ResourceTransferTargetFillPercent = resourceTransferTargetFillPercent,
            ResourceTransferSendWood = resourceTransferSendWood,
            ResourceTransferSendClay = resourceTransferSendClay,
            ResourceTransferSendIron = resourceTransferSendIron,
            ResourceTransferSendCrop = resourceTransferSendCrop,
            ReinforcementsEnabled = reinforcementsEnabled,
            ReinforcementsTargetVillageName = reinforcementsTargetVillageName,
            ReinforcementsSourceVillageNames = reinforcementsSourceVillageNames,
            ReinforcementsTroopRules = reinforcementsTroopRules,
            ReinforcementsSendMinMinutes = reinforcementsSendIntervalHours,
            ReinforcementsSendMaxMinutes = reinforcementsSendVariationPercent,
            GithubReleasesUrl = source.GithubReleasesUrl,
            HumanLikeEnabled = source.HumanLikeEnabled,
            HumanLikeSpeed = source.HumanLikeSpeed,
            ActionPacingEnabled = actionPacingEnabled,
            ActionPacingTaskMinSeconds = actionPacingTaskMinSeconds,
            ActionPacingTaskMaxSeconds = actionPacingTaskMaxSeconds,
            ActionPacingPageLoadMinSeconds = actionPacingPageLoadMinSeconds,
            ActionPacingPageLoadMaxSeconds = actionPacingPageLoadMaxSeconds,
            ActionPacingClickMinSeconds = actionPacingClickMinSeconds,
            ActionPacingClickMaxSeconds = actionPacingClickMaxSeconds,
            ActionPacingLoopMinSeconds = actionPacingLoopMinSeconds,
            ActionPacingLoopMaxSeconds = actionPacingLoopMaxSeconds,
            FarmListStepDelayMinSeconds = farmListStepDelayMinSeconds,
            FarmListStepDelayMaxSeconds = Math.Max(farmListStepDelayMinSeconds, farmListStepDelayMaxSeconds),
            ActionPacingIdleBreakEnabled = source.ActionPacingIdleBreakEnabled,
            ActionPacingIdleBreakIntervalMinMinutes = source.ActionPacingIdleBreakIntervalMinMinutes,
            ActionPacingIdleBreakIntervalMaxMinutes = source.ActionPacingIdleBreakIntervalMaxMinutes,
            ActionPacingIdleBreakDurationMinMinutes = source.ActionPacingIdleBreakDurationMinMinutes,
            ActionPacingIdleBreakDurationMaxMinutes = source.ActionPacingIdleBreakDurationMaxMinutes,
            ActionPacingIdleBrowseEnabled = source.ActionPacingIdleBrowseEnabled,
            ActionPacingIdleBrowseIntervalMinMinutes = source.ActionPacingIdleBrowseIntervalMinMinutes,
            ActionPacingIdleBrowseIntervalMaxMinutes = source.ActionPacingIdleBrowseIntervalMaxMinutes,
            ActionPacingIdleBrowsePageMap = source.ActionPacingIdleBrowsePageMap,
            ActionPacingIdleBrowsePageStatistics = source.ActionPacingIdleBrowsePageStatistics,
            ActionPacingIdleBrowsePageStatisticsHero = source.ActionPacingIdleBrowsePageStatisticsHero,
            ActionPacingIdleBrowsePageStatisticsTop10 = source.ActionPacingIdleBrowsePageStatisticsTop10,
            ActionPacingIdleBrowsePageStatisticsDefenders = source.ActionPacingIdleBrowsePageStatisticsDefenders,
            ActionPacingIdleBrowsePageStatisticsAttackers = source.ActionPacingIdleBrowsePageStatisticsAttackers,
            ActionPacingIdleBrowsePageReports = source.ActionPacingIdleBrowsePageReports,
            ActionPacingIdleBrowsePageMessages = source.ActionPacingIdleBrowsePageMessages,
            ConstructionHumanizeDelayEnabled = source.ConstructionHumanizeDelayEnabled,
            ConstructionHumanizeQueuePercentMin = source.ConstructionHumanizeQueuePercentMin,
            ConstructionHumanizeQueuePercentMax = source.ConstructionHumanizeQueuePercentMax,
            ConstructionHumanizeMaxDelayMinutes = source.ConstructionHumanizeMaxDelayMinutes,
            ConstructionHumanizeNoPlusMinMinutes = source.ConstructionHumanizeNoPlusMinMinutes,
            ConstructionHumanizeNoPlusMaxMinutes = source.ConstructionHumanizeNoPlusMaxMinutes,
            ConstructionPreSleepFill = construction.ConstructionPreSleepFill,
            ConstructionLoginFill = construction.ConstructionLoginFill,
            TargetVillageName = targetVillageName,
            TargetVillageUrl = targetVillageUrl,
            AllowGoldSpending = source.AllowGoldSpending,
            AllowSilverSpending = source.AllowSilverSpending,
            GoldLimit = source.GoldLimit,
            SilverLimit = source.SilverLimit,
            ResourceUpgradeSlotId = resourceUpgradeSlotId,
            ResourceUpgradeTargetLevel = resourceUpgradeTargetLevel,
            ResourceUpgradeMaxAttempts = resourceUpgradeMaxAttempts,
            ResourceBuildStrategy = resourceBuildStrategy,
            SmithyUpgradeTargets = smithyUpgradeTargets,
            BuildingUpgradeSlotId = buildingUpgradeSlotId,
            BuildingUpgradeTargetLevel = buildingUpgradeTargetLevel,
            BuildingUpgradeMaxAttempts = buildingUpgradeMaxAttempts,
            BuildingConstructSlotId = buildingConstructSlotId,
            BuildingConstructGid = buildingConstructGid,
            BuildingConstructName = buildingConstructName,
            BuildingConstructAllowSlotFallback = construction.BuildingConstructAllowSlotFallback,
            BuildingConstructFallbackExcludedSlots = construction.BuildingConstructFallbackExcludedSlots,
            ConstructFasterEnabled = constructFasterEnabled,
            ConstructFasterMinBuildTimeEnabled = constructFasterMinBuildTimeEnabled,
            ConstructFasterMinBuildMinutes = constructFasterMinBuildMinutes,
            ConstructFasterRandomEnabled = constructFasterRandomEnabled,
            ConstructFasterRandomChancePercent = constructFasterRandomChancePercent,
            TargetBuildingSlotOrName = targetBuildingSlotOrName,
            TargetLevel = targetLevel,
            HeroMinHpForAdventure = heroMinHpForAdventure,
            HeroAutoRevive = heroAutoRevive,
            HeroAutoAssignPoints = heroAutoAssignPoints,
            HeroAutoUseOintments = heroAutoUseOintments,
            HeroStatPriority = heroStatPriority,
            HeroAdventurePickOrder = heroAdventurePickOrder,
            HeroContinuousAdventures = heroContinuousAdventures,
            IncreaseAdventuresToHard = increaseAdventuresToHard,
            ReduceAdventureTime = reduceAdventureTime,
            HeroAdventureVideoChancePercent = heroAdventureVideoChancePercent,
            AutoCollectTasksEnabled = autoCollectTasksEnabled,
            AutoCollectDailyQuestsEnabled = autoCollectDailyQuestsEnabled,
            ProductionBonusVideoEnabled = productionBonusVideoEnabled,
            CollectStepDelayMinSeconds = collectStepDelayMinSeconds,
            CollectStepDelayMaxSeconds = collectStepDelayMaxSeconds,
            HeroResourceTransferEnabled = heroResourceTransferEnabled,
            HeroResourceMaxUseEnabled = heroResourceMaxUseEnabled,
            HeroResourceMaxUsePerResource = heroResourceMaxUsePerResource,
            HeroResourceUseConstruction = heroResourceUseConstruction,
            HeroResourceUseSmithy = heroResourceUseSmithy,
            HeroResourceUseBrewery = heroResourceUseBrewery,
            HeroResourceUseTownHall = heroResourceUseTownHall,
            UpgradeSelectorProfile = upgradeSelectorProfile,
        };
    }

}
